CREATE TABLE "user_task"(
    "user_id" INTEGER NOT NULL,
    "task_id" INTEGER NOT NULL
);
ALTER TABLE public.user_task ADD CONSTRAINT user_task_pkey PRIMARY KEY (user_id,task_id);

CREATE TABLE "user"(
    "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "dob" TIME(0) WITHOUT TIME ZONE NOT NULL,
    "sex" VARCHAR(255) NULL,
    "address" VARCHAR(255) NULL,
    "phone" VARCHAR(255) NULL
);
ALTER TABLE
    "user" ADD PRIMARY KEY("user_id");
CREATE TABLE "task"(
    "task_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255) NULL,
    "start_date" TIME(0) WITHOUT TIME ZONE NOT NULL,
    "end_date" TIME(0) WITHOUT TIME ZONE NOT NULL,
    "status" VARCHAR(255) NOT NULL
);
ALTER TABLE
    "task" ADD PRIMARY KEY("task_id");
ALTER TABLE
    "user_task" ADD CONSTRAINT "user_task_task_id_foreign" FOREIGN KEY("task_id") REFERENCES "task"("task_id");
ALTER TABLE
    "user_task" ADD CONSTRAINT "user_task_user_id_foreign" FOREIGN KEY("user_id") REFERENCES "user"("user_id");